language: node_js

sudo: false

node_js:
  - "6"

before_script:
  - "export TZ=Europe/Warsaw"
  - 'npm run build'
  - 'git checkout master'
  - 'git commit --message "[skip ci] Travis build: $TRAVIS_BUILD_NUMBER" -- dist'
  - "git remote rm origin"
  - "git remote add origin https://${GITHUB_TOKEN}@github.com/retrolator/react-handsontable.git"
  - "git push --quiet --set-upstream origin master"
